version: "3.4"

x-common: &common
  image: grubykarol/locust:latest
  environment: &common-env
    ATTACKED_HOST: http://1.50.17.88
    LOCUST_FILE: /scripts/test_salmon.py
  volumes:
    - ./:/scripts

services:
  locust-master:
    <<: *common
    ports:
      - 8089:8089
    environment:
      <<: *common-env
      LOCUST_MODE: master
  
  locust-slave:
    <<: *common
    environment:
      <<: *common-env
      LOCUST_MODE: slave
      LOCUST_MASTER: locust-master

  locust-slave2:
    <<: *common
    environment:
      <<: *common-env
      LOCUST_MODE: slave
      LOCUST_MASTER: locust-master


  locust-slave3:
    <<: *common
    environment:
      <<: *common-env
      LOCUST_MODE: slave
      LOCUST_MASTER: locust-master